### ISSUE TITLE
Can't run script

### ISSUE THREAD

**Issue by OmarParham** [HNygard/norsk-lovtidend#1]
While trying to run script i've got numerous issues(errors, exceptions etc) is it fixable or is there updated version?

PHP 7.2.34 (cli) (built: Sep 30 2020 07:31:56) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by OmarParham** [comment]
php get.php:
2021-10-05 09:01:50 INFO ---    - GET https://lovdata.no/register/lovtidend?year=2021&offset=0
2021-10-05 09:01:52 INFO ---    Response size: 102430
PHP Fatal error:  Uncaught ErrorException: Undefined offset: 0 in norsk-lovtidend/get.php:446
Stack trace:
#0 norsk-lovtidend/get.php(446): {closure}(8, 'Undefined offse...', '/var/www/html/p...', 446, Array)
#1 norsk-lovtidend/get.php(64): readItems('\n<!DOCTYPE html...')
#2 {main}
  thrown in norsk-lovtidend/get.php on line 446

**Comment by HNygard** [comment]
Hi!

The markup of lovdata.no changed, so the parser stopped, as it should. I fixed it earlier this year in addition to updating the data set, but I did not push to github at that time. Just now pushed these changes (5b4c093d3..89cfd3fd1) so the git repo should be up to date on Github.

Running the script now to update the git repo with the latest data.

**Comment by HNygard** [comment]
I have now updated the downloaded data by running "php get.php":

https://github.com/HNygard/norsk-lovtidend/commit/bb7ccf6506dfb140bdf5e635fc5f9a974953a911
